<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>SpaceEditor.ico</ApplicationIcon>
	<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="SpaceEditor.ico" />
    <Resource Include="Resources\**\*.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AssimpNetter" Version="6.0.2" />
    <PackageReference Include="Castle.Core" Version="5.2.1" />
    <PackageReference Include="ClrDebug" Version="0.3.4" />
    <PackageReference Include="geometry4Sharp" Version="1.0.0" />
    <PackageReference Include="ILGPU" Version="1.5.3" />
    <PackageReference Include="Microsoft.Diagnostics.DbgShim" Version="9.0.621003" />
    <PackageReference Include="ObservableCollections" Version="3.3.3" />
    <PackageReference Include="PixiEditor.ColorPicker" Version="3.4.2" />
    <PackageReference Include="PropertyTools.Wpf" Version="3.1.0" />
    <PackageReference Include="ReflectionMagic" Version="5.0.1" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Data\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Update="Data\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>

	<Target Name="GenerateBuildInfo" BeforeTargets="BeforeCompile">
		<PropertyGroup>
			<BuildDateTime>$([System.DateTime]::UtcNow.ToString("yyyy-MM-ddTHH:mm:ssZ"))</BuildDateTime>
			<BuildInfoFile>$(IntermediateOutputPath)BuildInfo.g.cs</BuildInfoFile>
		</PropertyGroup>

		<WriteLinesToFile File="$(BuildInfoFile)" Lines="&#xD;&#xA;			    internal static class BuildInfo&#xD;&#xA;			    {&#xD;&#xA;			        public static DateTime BuildTimeUtc =&gt; DateTime.Parse(&quot;$(BuildDateTime)&quot;) %3B&#xD;&#xA;			    }&#xD;&#xA;			" Overwrite="true" />

		<ItemGroup>
			<Compile Include="$(BuildInfoFile)" />
		</ItemGroup>
	</Target>

	<Target Name="ZipPublishOutput" AfterTargets="Publish">
		<ItemGroup>
			<ZipOutputPath Include="$(PublishDir)..\..\$(MSBuildProjectName).zip" />
		</ItemGroup>

		<ZipDirectory SourceDirectory="$(PublishDir).." DestinationFile="@(ZipOutputPath)" />

		<RemoveDir Directories="$(PublishDir)" />

		<Move SourceFiles="@(ZipOutputPath)" DestinationFolder="$(PublishDir)" />

	</Target>

</Project>
